// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEM1hFYBPB_Afj4yQp-9VyuqWJZ_EK4FI',
    appId: '1:339572852906:web:49c210065b39590d1aa8d3',
    messagingSenderId: '339572852906',
    projectId: 'kasa-c0f0a',
    authDomain: 'kasa-c0f0a.firebaseapp.com',
    storageBucket: 'kasa-c0f0a.firebasestorage.app',
    measurementId: 'G-CCLMKSXH2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEW2ydqpub34PIAF5uTVwxvjFFKJPccwE',
    appId: '1:339572852906:android:b2bfbad6b46591d81aa8d3',
    messagingSenderId: '339572852906',
    projectId: 'kasa-c0f0a',
    storageBucket: 'kasa-c0f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHPZOrV0RtCkTc2yJzmyhRsFYIqVgNGs',
    appId: '1:339572852906:ios:7e45db5ae5980ae61aa8d3',
    messagingSenderId: '339572852906',
    projectId: 'kasa-c0f0a',
    storageBucket: 'kasa-c0f0a.firebasestorage.app',
    iosBundleId: 'com.example.kasaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHPZOrV0RtCkTc2yJzmyhRsFYIqVgNGs',
    appId: '1:339572852906:ios:7e45db5ae5980ae61aa8d3',
    messagingSenderId: '339572852906',
    projectId: 'kasa-c0f0a',
    storageBucket: 'kasa-c0f0a.firebasestorage.app',
    iosBundleId: 'com.example.kasaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEM1hFYBPB_Afj4yQp-9VyuqWJZ_EK4FI',
    appId: '1:339572852906:web:49c210065b39590d1aa8d3',
    messagingSenderId: '339572852906',
    projectId: 'kasa-c0f0a',
    authDomain: 'kasa-c0f0a.firebaseapp.com',
    storageBucket: 'kasa-c0f0a.firebasestorage.app',
    measurementId: 'G-CCLMKSXH2B',
  );
}
