name: Flutter iOS Build

workflows:
  ios-build:
    name: Build and Test Flutter App for iOS
    environment:
      vars:
        FLUTTER_HOME: $HOME/flutter
      xcode: latest
    actions:
      - name: Setup Flutter and Dependencies
        script: |
          #!/bin/bash

          cd "$CI_PRIMARY_REPOSITORY_PATH"

          echo "Cloning Flutter SDK..."
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable "$FLUTTER_HOME"
          export PATH="$PATH:$FLUTTER_HOME/bin"

          echo "Pre-caching Flutter iOS artifacts..."
          flutter precache --ios

          echo "Getting Flutter packages..."
          flutter pub get

          echo "Installing CocoaPods..."
          HOMEBREW_NO_AUTO_UPDATE=1 brew install cocoapods

          echo "Installing iOS Pods..."
          cd ios
          pod install --repo-update
          cd "$CI_PRIMARY_REPOSITORY_PATH"

      - name: Build Runner
        script: |
          #!/bin/bash
          cd "$CI_PRIMARY_REPOSITORY_PATH"
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Flutter iOS Build
        script: |
          #!/bin/bash
          cd "$CI_PRIMARY_REPOSITORY_PATH"
          flutter build ios --no-codesign -t lib/main.dart
